namespace DockerRunner
{
    /// <summary>
    /// Docker volume for persisting data generated by and used by docker containers.
    /// </summary>
    /// <remarks>See [Use volumes](https://docs.docker.com/storage/volumes/) for mor information.</remarks>
    public sealed class DockerVolume : DockerStorage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DockerVolume"/> class.
        /// </summary>
        /// <param name="name">The name of the volume. Docker automatically creates the volume if it does not yet exist.</param>
        /// <param name="destination">The path where the file or directory is mounted in the container.</param>
        public DockerVolume(string name, string destination)
        {
            Name = name;
            Destination = destination;
        }

        /// <summary>
        /// The name of the volume. Docker automatically creates the volume if it does not yet exist.
        /// </summary>
        public string Name { get; }
    }
}