name: Continuous Integration

on: push

env:
  Configuration: Release
  ContinuousIntegrationBuild: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  package:
    runs-on: ubuntu-latest
    name: Run tests and create NuGet package
    outputs:
      project-name: ${{ steps.git-tag-name.outputs.projectName }}
      tag-name: ${{ steps.git-tag-name.outputs.tag }}
      version: ${{ steps.dotnet-pack.outputs.version }}
      nupkg-filename: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
      release-body: ${{ steps.tag-message.outputs.release-notes }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get git tag name
        uses: olegtarasov/get-tag@v2.1
        id: git-tag-name
        with:
          tagRegex: "(?<projectName>.+)/(?<projectVersion>.+)"
          tagRegexGroup: 0
      - name: Retrieve cached NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build solution
        run: dotnet build
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1
      # Running tests on multiple frameworks is not properly supported with `dotnet test`:
      # - dotnet test on a multi-target projects logs only the last target @ https://github.com/microsoft/vstest/issues/1603
      # - Add Support for Templating in LogFileName @ https://github.com/Microsoft/vstest/issues/1876
      # - Fix - dotnet test on a multi-target projects logs only the last target @ https://github.com/microsoft/vstest/pull/1877
      # - Several problems are being caused by the new log file name timestamp @ https://github.com/microsoft/vstest/issues/1978
      # - [Revert] Fix for dotnet test on a multi-target projects logs only the last target @ https://github.com/microsoft/vstest/pull/1996
      # The "easiest" workaround for now is to explicitly run for each supported framework
      - name: Run tests (.NET Framework 4.7.2)
        run: dotnet test --no-build --framework net472 --logger "html;LogFileName=../TestResults-${{ runner.os }}-net472.html" --logger GitHubActions
      - name: Run tests (.NET 5.0)
        run: dotnet test --no-build --framework net5.0 --logger "html;LogFileName=../TestResults-${{ runner.os }}-net5.0.html" --logger GitHubActions
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: TestResults-${{ runner.os }}
          path: "**/TestResults-*.html"
      - name: Create NuGet package
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet pack --no-build src/${{ steps.git-tag-name.outputs.projectName }}/${{ steps.git-tag-name.outputs.projectName }}.csproj --output .
        id: dotnet-pack
      - name: Upload NuGet package artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
          path: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
      - name: Retrieve tag message
        run: |
          git fetch --tags --force
          RELEASE_NOTES=$(git tag --list ${{ steps.git-tag-name.outputs.tag }} --format='%(contents)')
          RELEASE_NOTES="${RELEASE_NOTES//'%'/%25}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/%0A}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/%0D}"
          echo "::set-output name=release-notes::$RELEASE_NOTES"
        id: tag-message
  publish:
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish NuGet package and create GitHub release
    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.package.outputs.nupkg-filename }}
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.package.outputs.tag-name }}
          release_name: ${{ needs.package.outputs.project-name }} ${{ needs.package.outputs.version }}
          body: ${{ needs.package.outputs.release-body }}
          draft: false
          prerelease: ${{ contains(needs.package.outputs.version, '-') }}
      - name: Publish NuGet package on nuget.org
        run: dotnet nuget push ${{ needs.package.outputs.nupkg-filename }} --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET_API_KEY }}"
