name: Continuous Integration

on: push

env:
  Configuration: Release
  ContinuousIntegrationBuild: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  package:
    runs-on: ubuntu-latest
    name: Run tests and create NuGet package
    outputs:
      project-name: ${{ steps.git-tag-name.outputs.projectName }}
      version: ${{ steps.dotnet-pack.outputs.version }}
      nupkg-filename: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
      release-body: ${{ steps.tag-message.outputs.release-notes }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get git tag name
        uses: olegtarasov/get-tag@v2.1
        id: git-tag-name
        with:
          tagRegex: "(?<projectName>.+)/(?<projectVersion>.+)" 
      - name: Retrieve cached NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: Restore NuGet packages
        run: dotnet restore --verbosity normal
      - name: Build solution
        run: dotnet build --verbosity normal
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Run tests
        if: false
        run: dotnet test --no-build --verbosity normal
      - name: Create NuGet package
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet pack src/${{ steps.git-tag-name.outputs.projectName }}/${{ steps.git-tag-name.outputs.projectName }}.csproj --output . --no-build --verbosity normal
        id: dotnet-pack
      - name: Upload NuGet package artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
          path: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
      - name: Retrieve tag message
        run: |
          git fetch --tags --force
          RELEASE_NOTES=$(git tag --list ${{ steps.dotnet-pack.outputs.version }} --format='%(contents)')
          RELEASE_NOTES="${RELEASE_NOTES//'%'/%25}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/%0A}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/%0D}"
          echo "::set-output name=release-notes::$RELEASE_NOTES"
        id: tag-message
  publish:
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish NuGet package and create GitHub release
    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.package.outputs.nupkg-filename }}
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.package.outputs.version }}
          release_name: Version ${{ needs.package.outputs.version }}
          body: ${{ needs.package.outputs.release-body }}
          draft: false
          prerelease: ${{ contains(needs.package.outputs.version, '-') }}
      - name: Publish NuGet package on nuget.org
        if: false
        run: dotnet nuget push ${{ needs.package.outputs.nupkg-filename }} --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET_API_KEY }}"
